---
title: "Join our group!"
description: |
  Postdoc in the genetics of febrile seizures and epilepsy.
date: 2023-08-01
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Are you interested in taking our research in the genetics of seizures to the next level? 

We now have an opening for a 2-year fully funded postdoc position in a collaborative setup between the Biobank Unit at Copenhagen University Hospital and Statens Serum Institut, home of the Danish National Biobank. You will work with the world's largest genetic data sets on febrile seizures to discover genetic variation associated with this common childhood disease and understand the connections to epilepsy genetics. 

You can read much more about the position and our group in the full [job ad](https://www.regionh.dk/job/s%C3%B8g-job/Sider/Region-Hovedstaden-soeger.aspx?positionid=250847). Feel free to get in touch for further information about the position.  

Genetics of febrile seizures and the similarities and differences with epilepsy genetics is one of our core research areas. Some of our previous work is described [here](https://feenstralab.github.io/research.html#febrile-seizures). 